import {
  Anchor,
  Bike,
  Bird,
  Book,
  BookOpen,
  Bot,
  Brush,
  Bug,
  Cake,
  Camera,
  Car,
  Cat,
  Cloud,
  Coffee,
  Compass,
  Crown,
  Dog,
  Droplet,
  Feather,
  Fish,
  Flame,
  Flower,
  Flower2,
  Gamepad2,
  Gem,
  Ghost,
  Gift,
  Globe,
  Guitar,
  Headphones,
  Heart,
  IceCreamCone,
  Leaf,
  Map as MapIcon,
  Moon,
  Mountain,
  MountainSnow,
  Music,
  Palette,
  PawPrint,
  Pencil,
  Pizza,
  Plane,
  Puzzle,
  Rabbit,
  Rainbow,
  Rocket,
  Sailboat,
  Ship,
  Snail,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Tent,
  TrainFront,
  TreePine,
  Trees,
  Trophy,
  Turtle,
  Wind,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * The curated profile-icon set (SPEC §11): a handful of friendly glyphs, all
 * STATICALLY imported — no lazy chunks, no search, no scroll. Keyed by lucide's
 * kebab name, which is what `Profile.icon` stores.
 */
export const PROFILE_ICONS: { name: string; Icon: LucideIcon }[] = [
  { name: 'mountain', Icon: Mountain },
  { name: 'mountain-snow', Icon: MountainSnow },
  { name: 'tree-pine', Icon: TreePine },
  { name: 'trees', Icon: Trees },
  { name: 'leaf', Icon: Leaf },
  { name: 'flower', Icon: Flower },
  { name: 'flower-2', Icon: Flower2 },
  { name: 'sprout', Icon: Sprout },
  { name: 'sun', Icon: Sun },
  { name: 'moon', Icon: Moon },
  { name: 'star', Icon: Star },
  { name: 'cloud', Icon: Cloud },
  { name: 'snowflake', Icon: Snowflake },
  { name: 'zap', Icon: Zap },
  { name: 'flame', Icon: Flame },
  { name: 'droplet', Icon: Droplet },
  { name: 'rainbow', Icon: Rainbow },
  { name: 'wind', Icon: Wind },
  { name: 'bird', Icon: Bird },
  { name: 'fish', Icon: Fish },
  { name: 'cat', Icon: Cat },
  { name: 'dog', Icon: Dog },
  { name: 'rabbit', Icon: Rabbit },
  { name: 'turtle', Icon: Turtle },
  { name: 'bug', Icon: Bug },
  { name: 'snail', Icon: Snail },
  { name: 'paw-print', Icon: PawPrint },
  { name: 'feather', Icon: Feather },
  { name: 'rocket', Icon: Rocket },
  { name: 'anchor', Icon: Anchor },
  { name: 'compass', Icon: Compass },
  { name: 'map', Icon: MapIcon },
  { name: 'tent', Icon: Tent },
  { name: 'camera', Icon: Camera },
  { name: 'music', Icon: Music },
  { name: 'headphones', Icon: Headphones },
  { name: 'palette', Icon: Palette },
  { name: 'brush', Icon: Brush },
  { name: 'pencil', Icon: Pencil },
  { name: 'book', Icon: Book },
  { name: 'book-open', Icon: BookOpen },
  { name: 'coffee', Icon: Coffee },
  { name: 'pizza', Icon: Pizza },
  { name: 'ice-cream-cone', Icon: IceCreamCone },
  { name: 'cake', Icon: Cake },
  { name: 'gift', Icon: Gift },
  { name: 'gamepad-2', Icon: Gamepad2 },
  { name: 'puzzle', Icon: Puzzle },
  { name: 'bike', Icon: Bike },
  { name: 'car', Icon: Car },
  { name: 'plane', Icon: Plane },
  { name: 'ship', Icon: Ship },
  { name: 'sailboat', Icon: Sailboat },
  { name: 'train-front', Icon: TrainFront },
  { name: 'heart', Icon: Heart },
  { name: 'sparkles', Icon: Sparkles },
  { name: 'crown', Icon: Crown },
  { name: 'gem', Icon: Gem },
  { name: 'trophy', Icon: Trophy },
  { name: 'ghost', Icon: Ghost },
  { name: 'bot', Icon: Bot },
  { name: 'globe', Icon: Globe },
  { name: 'guitar', Icon: Guitar },
];

/** Lookup a stored icon name → its component (for rendering the chosen glyph). */
export const PROFILE_ICON_BY_NAME: Record<string, LucideIcon> = Object.fromEntries(
  PROFILE_ICONS.map((i) => [i.name, i.Icon]),
);
