import { mkdirSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import type { PuddlePaths } from '../paths.js';

/**
 * Captured-env shell hooks (SPEC §4). Session shells are spawned with an
 * injected prompt hook that diffs the shell's exported environment at every
 * prompt against an in-memory baseline and reports changes over the OSC 7733
 * side-channel (see env-osc.ts), which the daemon parses and strips before
 * anything is recorded or broadcast. Baseline and last-reported state live
 * only in shell memory — the shell never writes values to disk.
 *
 * zsh is hooked via a ZDOTDIR shim directory whose zdot files chain to the
 * user's real ones; bash via --rcfile. Both restore the user's view of the
 * world once loaded, so `exec zsh`, nested shells, and child processes never
 * see the shim. Unsupported shells (fish, …) and bash < 4 (macOS /bin/bash
 * 3.2 has no associative arrays) degrade gracefully: a plain shell, no
 * capture — previously captured env is still injected at spawn.
 *
 * Hook sources are embedded strings written at boot (the claude-statusline.ts
 * precedent): the daemon builds with plain tsc and ships no static assets.
 */

/**
 * Names never captured: per-shell/terminal state, prompt machinery, and
 * identity vars whose capture would corrupt future spawns rather than help
 * them. The PUDDLE_ prefix is denied as a rule (hook control vars). Kept in
 * sync with the shell templates below, which interpolate SHELL_DENYLIST;
 * SessionService re-checks daemon-side via isDeniedEnvName (defence in depth).
 */
export const ENV_CAPTURE_DENYLIST: ReadonlySet<string> = new Set([
  'PWD',
  'OLDPWD',
  'SHLVL',
  '_',
  'PS1',
  'PS2',
  'PROMPT',
  'PROMPT_COMMAND',
  'TERM',
  'TERMINFO',
  'COLUMNS',
  'LINES',
  'ZDOTDIR',
  'HOME',
  'SHELL',
  'USER',
  'LOGNAME',
  'TERM_PROGRAM',
  'TERM_PROGRAM_VERSION',
  'TERM_SESSION_ID',
]);

export function isDeniedEnvName(name: string): boolean {
  return name.startsWith('PUDDLE_') || ENV_CAPTURE_DENYLIST.has(name);
}

const SHELL_DENYLIST = [...ENV_CAPTURE_DENYLIST].join(' ');

/** Raw values above this are skipped shell-side; the daemon re-enforces by byte (SPEC §4). */
const MAX_VALUE_CHARS = 32 * 1024;

/* eslint-disable no-useless-escape -- the templates below are shell, not JS */

const zshEnvReport =
  () => `# Generated by puddle at daemon boot — do not edit (captured-env hook, SPEC §4).
# Reports exported-variable changes at each prompt over OSC 7733. Fails safe:
# any missing prerequisite means no capture and an otherwise normal shell.
zmodload -i zsh/parameter 2>/dev/null || return 0
autoload -Uz add-zsh-hook 2>/dev/null || return 0
command -v base64 >/dev/null 2>&1 || return 0

typeset -ga _puddle_env_denied
_puddle_env_denied=( ${SHELL_DENYLIST} )
typeset -gA _puddle_env_last _puddle_env_now

_puddle_env_scan() {
  _puddle_env_now=()
  local k t
  for k in \${(k)parameters}; do
    t=\$parameters[\$k]
    [[ \$t == *export* ]] || continue
    [[ \$t == *array* || \$t == *association* ]] && continue
    [[ \$k == PUDDLE_* ]] && continue
    (( \${_puddle_env_denied[(Ie)\$k]} )) && continue
    (( \${#\${(P)k}} > ${MAX_VALUE_CHARS} )) && continue
    _puddle_env_now[\$k]=\${(P)k}
  done
}

_puddle_env_b64() { printf %s "\$1" | command base64 | command tr -d '\\n'; }

_puddle_env_report() {
  _puddle_env_scan
  local k
  for k in \${(k)_puddle_env_now}; do
    if (( ! \${+_puddle_env_last[\$k]} )) || [[ \${_puddle_env_last[\$k]} != \${_puddle_env_now[\$k]} ]]; then
      printf '\\033]7733;set;%s;%s\\007' "\$(_puddle_env_b64 "\$k")" "\$(_puddle_env_b64 "\${_puddle_env_now[\$k]}")"
    fi
  done
  for k in \${(k)_puddle_env_last}; do
    if (( ! \${+_puddle_env_now[\$k]} )); then
      printf '\\033]7733;unset;%s\\007' "\$(_puddle_env_b64 "\$k")"
    fi
  done
  _puddle_env_last=("\${(@kv)_puddle_env_now}")
}

# Seed the baseline AFTER the user's rc ran: rc-set exports (and re-injected
# captured vars) are baseline, not deltas — no feedback loop on respawn.
_puddle_env_scan
_puddle_env_last=("\${(@kv)_puddle_env_now}")
add-zsh-hook precmd _puddle_env_report
`;

const zshZshenv = (
  zshDir: string,
) => `# Generated by puddle at daemon boot — do not edit (captured-env hook, SPEC §4).
# Puddle spawned this shell with ZDOTDIR pointed here; hand the user their real
# environment back, remembering what they had so .zshrc can restore it exactly.
if [[ -n \${PUDDLE_ORIG_ZDOTDIR-} ]]; then
  ZDOTDIR=\$PUDDLE_ORIG_ZDOTDIR
else
  unset ZDOTDIR
fi
unset PUDDLE_ORIG_ZDOTDIR
[[ -f "\${ZDOTDIR:-\$HOME}/.zshenv" ]] && builtin source "\${ZDOTDIR:-\$HOME}/.zshenv"
# The user's .zshenv may itself repoint ZDOTDIR — honour that as their choice.
typeset -g _puddle_user_had_zdotdir=\${+ZDOTDIR}
typeset -g _puddle_user_zdotdir=\${ZDOTDIR-}
ZDOTDIR=${JSON.stringify(zshDir)}
`;

const zshZprofile = (
  zshDir: string,
) => `# Generated by puddle at daemon boot — do not edit (captured-env hook, SPEC §4).
if (( _puddle_user_had_zdotdir )); then ZDOTDIR=\$_puddle_user_zdotdir; else unset ZDOTDIR; fi
[[ -f "\${ZDOTDIR:-\$HOME}/.zprofile" ]] && builtin source "\${ZDOTDIR:-\$HOME}/.zprofile"
typeset -g _puddle_user_had_zdotdir=\${+ZDOTDIR}
typeset -g _puddle_user_zdotdir=\${ZDOTDIR-}
ZDOTDIR=${JSON.stringify(zshDir)}
`;

const zshZshrc = (
  zshDir: string,
) => `# Generated by puddle at daemon boot — do not edit (captured-env hook, SPEC §4).
if (( _puddle_user_had_zdotdir )); then ZDOTDIR=\$_puddle_user_zdotdir; else unset ZDOTDIR; fi
[[ -f "\${ZDOTDIR:-\$HOME}/.zshrc" ]] && builtin source "\${ZDOTDIR:-\$HOME}/.zshrc"
# ZDOTDIR now holds the user's value (or their rc's choice) permanently —
# exec'd shells, nested zsh, and children must never see the puddle shim.
builtin source ${JSON.stringify(join(zshDir, 'env-report.zsh'))}
unset _puddle_user_had_zdotdir _puddle_user_zdotdir
`;

const zshZlogin = (
  zshDir: string,
) => `# Generated by puddle at daemon boot — do not edit (captured-env hook, SPEC §4).
# .zshrc restores the user's ZDOTDIR before zsh reads .zlogin, so this file is
# normally unreachable; the guard prevents self-sourcing if it ever is.
[[ -f "\${ZDOTDIR:-\$HOME}/.zlogin" && "\${ZDOTDIR:-\$HOME}" != ${JSON.stringify(zshDir)} ]] && builtin source "\${ZDOTDIR:-\$HOME}/.zlogin"
`;

const bashRcfile =
  () => `# Generated by puddle at daemon boot — do not edit (captured-env hook, SPEC §4).
# Spawned as: bash --rcfile <this file>. First restore normal behaviour…
[ -f "\$HOME/.bashrc" ] && . "\$HOME/.bashrc"

# …then hook the prompt, when this bash can (needs associative arrays: bash
# ≥ 4 — macOS /bin/bash 3.2 gets a normal shell with no capture).
if [ -n "\${BASH_VERSINFO-}" ] && [ "\${BASH_VERSINFO[0]}" -ge 4 ] && command -v base64 >/dev/null 2>&1; then
  _puddle_env_denied=' ${SHELL_DENYLIST} '

  declare -A _puddle_env_last=()

  _puddle_env_b64() { printf %s "\$1" | command base64 | command tr -d '\\n'; }

  _puddle_env_report() {
    local k v
    declare -A _puddle_now=()
    for k in \$(compgen -e); do
      case \$k in PUDDLE_*) continue ;; esac
      [[ \$_puddle_env_denied == *" \$k "* ]] && continue
      v=\${!k}
      (( \${#v} > ${MAX_VALUE_CHARS} )) && continue
      _puddle_now[\$k]=\$v
    done
    for k in "\${!_puddle_now[@]}"; do
      if [[ -z \${_puddle_env_last[\$k]+x} || \${_puddle_env_last[\$k]} != "\${_puddle_now[\$k]}" ]]; then
        printf '\\033]7733;set;%s;%s\\007' "\$(_puddle_env_b64 "\$k")" "\$(_puddle_env_b64 "\${_puddle_now[\$k]}")"
      fi
    done
    for k in "\${!_puddle_env_last[@]}"; do
      if [[ -z \${_puddle_now[\$k]+x} ]]; then
        printf '\\033]7733;unset;%s\\007' "\$(_puddle_env_b64 "\$k")"
      fi
    done
    _puddle_env_last=()
    for k in "\${!_puddle_now[@]}"; do _puddle_env_last[\$k]=\${_puddle_now[\$k]}; done
  }

  # Seed the baseline AFTER ~/.bashrc ran (rc exports and re-injected captured
  # vars are baseline, not deltas), then prepend so a user PROMPT_COMMAND keeps
  # running after ours.
  for _puddle_k in \$(compgen -e); do
    case \$_puddle_k in PUDDLE_*) continue ;; esac
    [[ \$_puddle_env_denied == *" \$_puddle_k "* ]] && continue
    _puddle_env_v=\${!_puddle_k}
    (( \${#_puddle_env_v} > ${MAX_VALUE_CHARS} )) && continue
    _puddle_env_last[\$_puddle_k]=\$_puddle_env_v
  done
  unset _puddle_k _puddle_env_v
  PROMPT_COMMAND="_puddle_env_report\${PROMPT_COMMAND:+;\$PROMPT_COMMAND}"
fi
`;

/* eslint-enable no-useless-escape */

export interface ShellSpawnConfig {
  args: string[];
  env: Record<string, string>;
}

export class ShellHooks {
  constructor(
    private readonly zshDir: string,
    private readonly bashRc: string,
  ) {}

  /**
   * Extra args/env that arm the capture hook for a session shell. Dispatch is
   * by binary name; anything unrecognised spawns plain (no capture).
   */
  spawnConfig(shellPath: string): ShellSpawnConfig {
    const shell = basename(shellPath);
    if (shell === 'zsh') {
      const orig = process.env.ZDOTDIR;
      return {
        args: [],
        // PUDDLE_ORIG_ZDOTDIR carries the user's own ZDOTDIR through the shim;
        // its absence is the "user had none" sentinel, so only set it when real.
        env: { ZDOTDIR: this.zshDir, ...(orig ? { PUDDLE_ORIG_ZDOTDIR: orig } : {}) },
      };
    }
    if (shell === 'bash') return { args: ['--rcfile', this.bashRc], env: {} };
    return { args: [], env: {} };
  }
}

/**
 * Write the hook scripts under ~/.puddle/shell-hooks (regenerated every boot,
 * so upgrades refresh them). Files are sourced, never executed: 0600 in 0700
 * dirs.
 */
export function installShellHooks(paths: PuddlePaths): ShellHooks {
  const zshDir = join(paths.shellHooksDir, 'zsh');
  const bashDir = join(paths.shellHooksDir, 'bash');
  mkdirSync(zshDir, { recursive: true, mode: 0o700 });
  mkdirSync(bashDir, { recursive: true, mode: 0o700 });
  const write = (file: string, content: string) => writeFileSync(file, content, { mode: 0o600 });
  write(join(zshDir, '.zshenv'), zshZshenv(zshDir));
  write(join(zshDir, '.zprofile'), zshZprofile(zshDir));
  write(join(zshDir, '.zshrc'), zshZshrc(zshDir));
  write(join(zshDir, '.zlogin'), zshZlogin(zshDir));
  write(join(zshDir, 'env-report.zsh'), zshEnvReport());
  const bashRc = join(bashDir, 'bashrc.bash');
  write(bashRc, bashRcfile());
  return new ShellHooks(zshDir, bashRc);
}
